orangepages/views/friend.py
from flask import request, make_response, redirect
from flask import Blueprint, render_template
from orangepages.models.models import db, User, NType, Notification, Relationship
from flask_cas_fix import login_required
from sqlalchemy import exc, and_

from orangepages.views.util import cur_user, cur_uid, render, user_required
import orangepages.models.statuses as st


page = Blueprint('friend', __name__)


@page.route('/profile/friend-request', methods=['POST'])
@user_required
def friend_request():
    user1 = cur_user()
    friend_uid = request.form.get('content')
    user2 = User.query.get(friend_uid)

    if user1.uid < user2.uid:
        status = st.request1_2
        updateRelation(user1, user2, status)

    if user2.uid < user1.uid:
        status = st.request2_1
        updateRelation(user1, user2, status)

    notif = Notification(user1, user2, NType.REQUESTED)

    return redirect(request.referrer)



@page.route('/profile/add-friend', methods=['POST'])
@user_required
def add_friend():
    user1 = cur_user()
    friend_uid = request.form.get('content')
    user2 = User.query.get(friend_uid)

    status = st.friends
    updateRelation(user1, user2, status)

    notif = Notification(user1, user2, NType.ACCEPTED)

    return redirect(request.referrer)

@page.route('/profile/unfriend', methods=['POST'])
@user_required
def unfriend():
    user1 = cur_user()
    friend_uid = request.form.get('content')
    user2 = User.query.get(friend_uid)

    status = st.unfriend
    updateRelation(user1, user2, status)

    return redirect(request.referrer)

# @page.route('/friends-list', methods=['GET'])
# def friends_list():
#     user = cur_user()
#     friend_list = user.friend_list()
#     return render('friends.html',
#     friend_list = friend_list, lookup_user=user)

@page.route('/profile/<string:lookup_id>/friends-list', methods=['GET'])
@user_required
def friends_list(lookup_id):
    user = User.query.get(lookup_id)
    if user is None:
        return render('message.html',
            title='Error',
            message="This user doesn't exist.")


    friend_list = user.friend_list()
    return render('friends.html',
    friend_list = friend_list, lookup_user=user)



# ---

# util
def updateRelation(user1, user2, status):
    if user1.uid < user2.uid:
        try: rel = Relationship.query.filter(and_(Relationship.user1.has(uid=user1.uid), Relationship.user2.has(uid=user2.uid))).all()[0]
        except:
            rel = Relationship(user1, user2, status)
        rel.change_status(status)

    elif user2.uid < user1.uid:
        try: rel = Relationship.query.filter(and_(Relationship.user1.has(uid=user2.uid), Relationship.user2.has(uid=user1.uid))).all()[0]
        except:
            rel = Relationship(user2, user1, status)
        rel.change_status(status)
    return rel

orangepages/views/post.py
from flask import request, redirect, make_response
from datetime import datetime
from flask import Blueprint, render_template, send_from_directory
from orangepages.models.models import db, User, Group, Post, Comment, Tag, NType, Notification
from orangepages.views.util import cur_user, cur_uid, render, user_required
from orangepages import app
import os
# from flask_login import current_user, login_required


page = Blueprint('post_page', __name__)


@page.route('/create-post', methods=['POST'])
@user_required
def create_post():

    user = cur_user()
    post = Post(user)

    edit_post_util(post, request)

    return redirect("/feed")

@page.route('/post/<int:postid>/edit', methods=['POST', 'GET'])
@user_required
def edit_post(postid):
    post = Post.query.get(postid)

    if post is None:
        return render('message.html',
            title='Error',
            message="This post doesn't exist.")

    if request.method=='GET' or cur_user() is not post.creator:
        return redirect("/post/"+str(postid))

    post.update_last_edit()
    edit_post_util(post, request)

    return redirect('/post/'+ str(post.pid))

def edit_post_util(post, request):
    user = cur_user()
    content = request.form.get('content')

    # TAGS Parse tags and add them - list of tag STRINGS
    tags = []
    tags_raw =  request.form.get('tags')
    print(tags_raw)
    if tags_raw is not None:

        tags_str = tags_raw.split(' ')

        for tag in tags_str:
            if tag != "":
                tags.append(tag)

    # GROUPS
    # groups = []
    visibility = request.form.get('visibility')

    if visibility is not None:
        post.set_visibility(visibility)
    # hardcoded, one group only rn
    # if visibility == 'Public':
    #     groups.append(Group.query.get(1))
    # elif visibility == 'Friends':
    #     groups.append(user._groups[0]) # friends group
    #
    # groups.append(user._groups[1]) # just me group

    # TAGGING PEOPLE
    # In content, look for the string right after the @ sign
    if content:
        after_sign = content.split("@")
        # determine if string is a valid netid

        for str in after_sign:
            split_str = str.split(' ',  2)
            possible_netid = split_str[0]
            possible_user = User.query.get(possible_netid)

            if possible_user is not None: #and possible_user is not cur_user():
                notif = Notification(user, possible_user, NType.TAGGED, post)
                content = content.replace('@' + possible_netid, "<a href='/profile/" + possible_netid + "' class='tag-link'>@" + possible_netid + "</a>")

            elif len(split_str) > 1:
                possible_firstname = split_str[0]
                possible_lastname = split_str[1]

                p = db.session.query(User)
                p = p.filter(User.firstname == possible_firstname)
                p = p.filter(User.lastname == possible_lastname)

                for tagged_user in p.all():
                    #if tagged_user is not cur_user():
                    name = "@" + tagged_user.firstname + " " + tagged_user.lastname
                    content = content.replace(name, "<a href='/profile/" + tagged_user.uid + "' class='tag-link'>" + name + "</a>")
                    notif = Notification(user, tagged_user, NType.TAGGED, post)

    # overwrite image or delete img
    # del_img = request.form.get('delete_img')

    # if (del_img is not None) and (del_img == "on"):
    #     post.del_img()

    delete_img = request.form.get('delete-img')
    if delete_img == 'delete':
        post.del_img()

    if "image" in request.files:
        image = request.files["image"]
        if image.filename is not '':
            post.add_img(image)

    post.update_info(content, groups=[], tags=tags)

    db.session.commit()
    print(post.tags)

@page.route('/post/<int:postid>/delete', methods=['POST', 'GET'])
@user_required
def delete_post(postid):
    user = cur_user()
    post = Post.query.get(postid)
    if post.creator is user:
        post.delete()
    return redirect("/feed")

@page.route('/comment/<int:commentid>/delete', methods=['POST', 'GET'])
@user_required
def delete_comment(commentid):
    user = cur_user()
    comment = Comment.query.get(commentid)
    postid = comment.postid
    if comment.creator is user:
        comment.delete()
    return redirect('/post/'+ str(postid))


@page.route('/post/<int:postid>', methods=['GET', 'POST'])
@user_required
def view_post(postid):
    post = Post.query.get(postid)
    if post is None:
        return render('message.html',
            title='Error',
            message="This post doesn't exist.")

    comments = post.get_comments()
    num_likers = len(post.get_likers())
    tags = post.get_tags()
    t = datetime.utcnow()

    return render("post_details.html", post=post, t_first=t, t_last=post.date, comments=comments,
    num_likers = num_likers, tags=tags)

@page.route('/post-refresh', methods=['POST'])
@user_required
def post_refresh():
    postid = request.form.get('postid')
    post = Post.query.get(postid)
    if post is None:
        return render('message.html',
            title='Error',
            message="This post doesn't exist.")


    return render('post.html', post=post)

@page.route('/post-preview-refresh', methods=['POST'])
@user_required
def post_prev_refresh():
    postid = request.form.get('postid')
    post = Post.query.get(postid)
    if post is None:
        return render('message.html',
            title='Error',
            message="This post doesn't exist.")


    return render('post_preview.html', post=post)




@page.route('/post/<int:postid>/comment', methods=['POST'])
@user_required
def comment(postid):
    post = Post.query.get(postid)
    if post is None:
        return render('message.html',
            title='Error',
            message="This post doesn't exist.")

    user = cur_user()
    content = request.form.get('content')

    comment = Comment(postid, content, user)

    if(post.creator is not user):
        notif = Notification(user, post.creator, NType.COMMENTED, post)

    db.session.commit()

    return redirect('/post/' + str(postid))

# @page.route('/post/<int:post_id>', methods=['GET'])
# def feed_post(post_id):
#     # # TODO:
#     return

@page.route('/post/<int:post_id>/like')
@user_required
def like(post_id):
    post = Post.query.get(post_id)
    if post is None:
        return render('message.html',
            title='Error',
            message="This post doesn't exist.")

    user = cur_user()

    if user.liked_post(post_id):
        post.unlike(user)
    else:
        post.add_like(user)
        if(post.creator is not user):
            notif = Notification(user, post.creator, NType.LIKED, post)

    db.session.commit()

    return ''
    # return redirect(request.referrer)

# Might need FIXME
@page.route('/post/<int:post_id>/tag', methods=['POST'])
@user_required
def add_tag(post_id):
    post = Post.query.get(post_id)
    if post is None:
        return render('message.html',
            title='Error',
            message="This post doesn't exist.")

    tag_str = request.form.get('content')

    post.add_tag_str(tag_str)

    return redirect(request.referrer)

# def get_tag(post_id):
#     post = Post.query.get(post_id)
#     tags = post.get_tags()
#
#     return redirect(request.referrer)

# @page.route('/post/<int:post_id>/likers', methods=['GET'])
# def likers(post_id):
#     post = Post.query.get(postid)
#     likers = post.get_likers()
#     likersStr = str(likers)
#
#     return render('message.html',
#         title='Success',
#         message=likersStr)

# @page.route('/post/<int:post_id>/num-likers', methods=['GET'])

orangepages/views/search.py
from flask import request, make_response, jsonify
from flask import Blueprint, render_template
from orangepages.models.models import User, Tag
from orangepages.views.util import render, cur_user, user_required
import re


page = Blueprint('testsearch', __name__)

@page.route('/search')
@user_required
def search_user():
    query = request.args.get('query')
    pattern = re.compile(r'\"(.+?)\"$')
    match = pattern.match(query)
    
    if match is not None:
        query_list = [query[1:-1]]
        exact = True
    else:
        query_list = request.args.get('query').split(' ')
        exact = False


    posts = search_tag(query_list)
    user_preview_list = cur_user().search(*query_list, exact=exact).all()
    query = ' '.join(query_list)

    return render('search.html', posts=posts,
    user_preview_list=user_preview_list, query=query, exact=exact)

# helper method
def search_tag(query_list):
    tagged_posts = []
    for query in query_list:
        print("hash", query)

        tags = Tag.query.filter_by(tid=query).all()
        if len(tags) == 0:
            posts = []
        else:
            for tag in tags:
                posts = tag.get_posts(cur_user())

        tagged_posts.extend(posts)

    return tagged_posts

@page.route('/autocomplete', methods=['GET'])
def autocomplete():
    query_list = request.args.get('query').split(' ')
    users = cur_user().search(*query_list, exact=False).all()
    results = [{'label':user.firstname + " " + user.lastname, 'value':user.uid} for user in users]
    return jsonify(results=results)

# @page.route('/searchbar-tag')
# def searchbar_tag():
#     return render('test/searchbar-tag.html')

orangepages/templates/about.html
<!DOCTYPE html>
<html class="no-js" lang="en">

<head>
    <title>OrangePages | About</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width,
    initial-scale=1">
    <!-- <meta http-equiv="refresh" content="20" /> -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

    <!--CSS-->
    <link rel="stylesheet" href="/static/css/bootstrap.css" type="text/css" />
    <link rel="stylesheet" href="/static/css/styles.css" type="text/css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
        integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous"
        type="text/css" />
    <link rel='stylesheet' href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        type="text/css" />
    <link rel="stylesheet" href="/static/css/feed.css" type="text/css" />

    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
    <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,800">

    <!--JS-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src='https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.5/jquery-ui.min.js'></script>
    <script src="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/static/js/feed.js"></script>

</head>

<body>
    {% include 'sidebar.html' %}

    <div id="content">
        {% include 'navbar.html' %}

        <!-- Main page -->

        <div class="col">
        </div>
        <div class="col" style="width: 600px; float: none; margin: 0 auto; padding-bottom:20px">
            <br/>
            <br/>
            <h2>About</h2>
            <br/>
            <div style="text-align:justify;">
            We believe that Princeton students want better and simpler ways to find and connect with each other. With this goal in mind, we want to create an intuitive, exciting new social networking platform specifically for Princeton Undergraduates. OrangePages would allow Princeton students to connect via posts and comments, find each other by classes, clubs, majors and many other criteria, and have complete control over their profile data and who can find them.
            </div>
            <br/>
        </div>
        <div class="col">
        </div>

    </div>

    </div>
</body>


<!-- jQuery Custom Scroller CDN -->
<script
    src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>


<script src="/static/js/sidebar.js"></script>

<script>
    document.getElementById('About').className = 'active';
</script>

</html>

orangepages/templates/feed.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>OrangePages | Feed</title>
  <meta name="viewport" content="width=device-width,
                  initial-scale=1">
  <!-- <meta http-equiv="refresh" content="20" /> -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">

  <!--CSS-->
  <link rel="stylesheet" href="/static/css/bootstrap.css" type="text/css" />
  <link rel="stylesheet" href="/static/css/styles.css" type="text/css" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
    integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous"
    type="text/css" />
  <link rel='stylesheet' href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    type="text/css" />
  <!-- <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css" rel="stylesheet" /> -->

  <!-- Scrollbar Custom CSS -->
  <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
  <!-- Fonts -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,800">

  <!--JS-->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <script src='https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.5/jquery-ui.min.js'></script>
  <script src="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="/static/js/feed.js"></script>
  <script type="text/javascript" src="/static/js/post-preview.js"></script>
  <script type="text/javascript" src="/static/js/timestamp.js"></script>
</head>

<body>



  <!-- Everything goes in a wrapper -->
  <div class="wrapper">

    {% include 'sidebar.html' %}

    <div id="content">
      {% include 'navbar.html' %}

      <div class="col">
      </div>
      <div class="col" style="width: 650px; float: none; margin: 0 auto;">

        <!-- Make a post -->
        <div class="col" id="main">
          <form action="create-post" method="post" enctype="multipart/form-data" id="create-post-form">
            <div class="post-card card border-left-20 border-right-20 border-top-0 rounded-0"
              style="margin-bottom: 10px;">
              <div class="container-fluid">


                <div class="row">
                  <!-- Profile photo -->
                  <div class="col" style="padding-top: 10px; -ms-flex: 0 0 40px; flex: 0 0 40px;">
                    {%if user._pic is none:%}
                    <i class="fa fa-user feed-profile rounded-circle"></i>
                    {%else:%}
                    <a href='profile/{{ user.uid }}'>
                      <img class="feed-profile rounded-circle"
                        src='https://res.cloudinary.com/hcfgcbhqf/image/upload/c_fill,h_120,w_120,g_face,r_10/{{user._pic}}.png'
                        alt="failed to load">
                    </a>
                    {%endif%}
                  </div>

                  <!-- Post input -->
                  <div class="col" style="padding: 10px">
                    <div class="field">
                      <textarea name="content" class="make-post form-control border-0" id="message" rows="3"
                        placeholder="Write a post..." maxlength="500"></textarea>
                    </div>
                  </div>
                </div>

                <!-- Tags -->
                <div class="row" style="padding-bottom: 5px">
                  <div class="col mb-1 collapse" id="tagsCollapse">
                    <input name="tags" id="form-tags-5" class="form-control noEnterSubmit"></input>
                  </div>
                </div>

                <div class="row">

                  <div class="col">
                    <!-- Upload image input -->
                    <div class="input-group-append">
                      <div id="up-img-btn">
                        <label for="upload" class="btn btn-light m-0 rounded-pill px-4 upload-image" id="post-button">
                          <i class="fa fa-cloud-upload text-muted"></i>
                          <span><small class="text-muted">Upload Image</small></span>
                        </label>
                      </div>
                      <button type="button" id="del-img-btn" class="btn btn-light m-0 rounded-pill px-4 upload-image" style="display:none;"><i class="fas fa-times mr-2 text-muted"></i><small class="text-muted">Delete image</small></button>
                    </div>
                  </div>
                  
                  <!-- This needs to be here in order for upload to work -->
                  <input id="upload" accept="image/*" type="file" name="image" onchange="readURL(this);" style="display: none">

                  <!-- Add tags -->
                  <div class="col">
                    <button class="btn btn-light m-0 rounded-pill px-4 upload-image" id="post-button" type="button"
                      data-toggle="collapse" data-target="#tagsCollapse" aria-expanded="false"
                      aria-controls="tagsCollapse"><i class="fas fa-hashtag text-muted"></i>
                      <span><small class="text-muted">Add Tags</small></span>
                    </button>
                  </div>

                  <div class="col">
                    <div class="btn-group" style="width:100%">
                      <select name="visibility" class="form-control" id="visibility">
                        <option>Public</option>
                        <option>Friends</option>
                        <option>Just me</option>
                      </select>
                    </div>
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col" style="margin-left: 20px; margin-right: 20px; margin-top: -10px">

                  <!-- (NEW) Uploaded image area-->
                  <div class="image-area mt-4"><img id="imageResult" src="#" alt="" class="img-fluid rounded shadow-sm mx-auto d-none"></div>

                </div>
              </div>

              <div class="row">

                <div class="col" style="margin: 10px">
                  <div class="field">
                    <button id="share" type="submit" class="btn btn-primary tag-pill" style="width: 100%; background-image: linear-gradient(to bottom right, #f58e31, #f5672c); border:none;"
                      onclick="disableButton(this)" disabled="disabled">Share</button>
                  </div>
                </div>
              </div>

          </form>
        </div>


        <hr style="margin-bottom: 0px">
        <div class="load-posts-div">
          <button id="load-new-posts" class="btn btn-light m-0 rounded-pill px-4"
            style="display:none; background: #f9f9f9;"></button>
        </div>
        <hr style="margin-top: 0px">

        <div id="posts">

          <!-- <button type="button" id="sidebarCollapse" class="btn btn-primary">
          <i class="fas fa-align-left"></i>
          <span>Toggle Sidebar</span>
        </button>

        There will be a create post button here
        ALSO I'M STILL WORKING ON EVERYTHING
        Hopefully it will look good soon -->
          <!-- TODO: if no posts, display a message -->
          {% if not posts: %}
          {% endif %}


          {% include 'feed_posts.html' %}

        </div>

        <div class="post-card card border-left-20 border-bottom-20 border-right-10 rounded-0"
          style="border-bottom-width: 10px;">
        </div>
      </div>
    </div>

  </div>

</body>

<body>

  <!-- jQuery CDN - Slim version (=without AJAX) -->
  <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script> -->
  <!-- jQuery Custom Scroller CDN -->
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>

  <script src="/static/js/sidebar.js"></script>
  <script src="/static/js/tags.js"></script>
  <script src="/static/js/upload.js"></script>

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.12/dist/js/bootstrap-select.min.js"></script>

  <script>
    var loadFile = function (event) {
      var image = document.getElementById('imageResult');
      image.src = URL.createObjectURL(event.target.files[0]);
    };
  </script>

  <script>
    document.getElementById('Home').className = 'active';
  </script>

  <script src="/static/js/disable-share.js"></script>

  <script type="text/javascript">
    $(function () {
      $('#create-post-form').submit(function () {
        $('#share', this)
          .attr('disabled', 'disabled');
        document.getElementById("share").innerHTML = "Sharing...";
        return true;
      });
    });
  </script>

</body>

</html>

orangepages/templates/feed_posts.html
{% for post in posts: %}
    <div id="post{{post.pid}}">
        {% include 'post_preview.html' %}
    </div>
{% endfor %}


<script>
  var t_first = '{{t_first}}';
  var t_last = '{{t_last}}';
</script>

orangepages/templates/footer.html
<br>
<footer class="footer container card gedf-card" style="text-align: center; color: white">
  <br>
  <span><a href="/about" class="text-warning">About</a> |
    <a href="/contact" class="text-warning">Contact Us</a>
    <p>OrangePages version -1.0.</p>
  </span>
</footer>

orangepages/templates/navbar.html
  <!-- Popper.JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
    integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
    crossorigin="anonymous"></script>

    <!-- Bootstrap JS -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
    integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
    crossorigin="anonymous"></script>

  <!-- NProgress loading bar -->
  <script src='/static/js/nprogress.js'></script>
  <script>NProgress.configure({ ease: 'ease', speed: 500 });
          NProgress.start();NProgress.done();</script>

 <!-- Navigation -->
<nav class="navbar main-nav" style="background-color: white;">
  <div class="row w-100">
    <div class="col" style="-ms-flex: 0 0 40px; flex: 0 0 40px;">
      <button type="button" id="sidebarCollapse" class="btn" style="background-color: white; color: var(--new-orange); outline: none;">
          <i class="fas fa-align-left"></i>
       </button>
    </div>

    <div class="col" style="text-align: center; max-width: calc(100% - 80px);">
      <form action="/search" class="navbar-form navbar-search text-center mx-auto" method="get" style="display:block; width:500px; max-width: 100%">
        <div class="row">
          <div class="col">
            <input class="navbar-search form-control w-100" type="text" id="autocomplete" name="query" placeholder="Search OrangePages" aria-label="Search">
          </div>
          <div class="col" style="-ms-flex: 0 0 20px; flex: 0 0 20px; margin-left: -20px">     
            <button type="submit" class="btn" style="background-color: white; color: var(--new-orange); outline: none;">
              <i class="fas fa-search"></i>
            </button>
          </div>
          <div class="col-1 hidden-xs" style="-ms-flex: 0 0 20px; flex: 0 0 20px; margin-left: -20px; margin-top: 6px; color: var(--new-orange);">
            <i data-toggle="tooltip" data-placement="bottom" title='You can search for people by any profile field, or for posts by a tag. For exact matches, use double quotes.
            For example, enter "NJ" to find people from New Jersey.' class="fas fa-info-circle"></i>
          </div>
        </div>
      </form>
    </div>

    <div class="col" style="-ms-flex: 0 0 20px; flex: 0 0 20px;">
    </div>

  </div>
</nav>

<script>
  jQuery.curCSS = function(element, prop, val) {
    return jQuery(element).css(prop, val);
  };
  jQuery.ui.autocomplete.prototype._resizeMenu = function () {
  var ul = this.menu.element;
  ul.outerWidth(this.element.outerWidth());
  }

  $(document).ready(function(){
 $('#autocomplete').autocomplete({
  source:function(request, response) {
            $.getJSON("{{url_for('testsearch.autocomplete')}}",{
                query: request.term, 
            }, function(data) {
                response(data.results.slice(0, 8)); // matching_results from jsonify
            });
        },  
  select : function(event, ui){
        // You may need to change this part, as I don't know the exact values:
        window.location.href = "/profile/" + ui.item.value;
    }
 })
});

$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>